### ISSUE TITLE
Use of mutable kwargs throughout psiflow

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [molmod/psiflow#14]
https://github.com/molmod/psiflow/blob/e011c2b1712396d61550717fb6e30c7b75aec290/psiflow/models/base.py#L28-L34

There are many instances in Psiflow where the default arguments are mutable objects. Is this intentional? I would imagine that this would be [particularly undesirable](https://docs.python-guide.org/writing/gotchas/#:~:text=Python's%20default%20arguments%20are%20evaluated,to%20the%20function%20as%20well) and that one should do `inputs: List[file] | None = None` followed by something like `inputs = {} if inputs is None else inputs` in the function definition. Are these kwargs intentionally mutable, out of curiosity?

**Comment by svandenhaute** [comment]
Not really, this is inspired by the examples in the [Parsl docs](https://parsl.readthedocs.io/en/stable/1-parsl-introduction.html#Passing-data).
I see your point about this being undesirable. I seem to remember that Parsl demands these arguments to be of type `list` at all times. I guess we could change all defaults to None, but then take care that each time we're calling the `python_app`, we supply `inputs` and `outputs` as potentially-empty lists such that Parsl won't complain.
Alternatively, we use a `default_factory` as is done in some of the dataclasses in which mutable defaults are used as well, though I don't think this is standard Python practice for functions.

**Comment by Andrew-S-Rosen** [comment]
Ah, I see. So this related to a Parsl constraint with the `inputs` and `outputs` kwargs. I'm going to inquire on the Slack channel about this one because the Parsl docs don't really promote best-practices if there are constraints. It could make sense for Parsl to accept `None` and then assume it's `{}`.

**Comment by Andrew-S-Rosen** [comment]
@svandenhaute: here is a follow up https://github.com/Parsl/parsl/issues/2925#issuecomment-1777334808.

**Comment by svandenhaute** [comment]
Yeah, I just disabled flake8 to complain about it for now until this is sorted in Parsl.
