### ISSUE TITLE
Change configuration file to YAML format for better readability

### ISSUE THREAD

**Issue by svandenhaute** [molmod/psiflow#19]
The execution configuration is entirely declarative; it does not involve any computations. As such, formatting it as a Python script is rather misleading, and might make it look more complicated than it actually is.
It should be fairly trivial to convert this into yaml using Pydantic.

**Comment by Andrew-S-Rosen** [comment]
This is a great idea! It's pretty straightfoward with `pydantic-settings`. 😄
