### ISSUE TITLE
Possible typo in README

### ISSUE THREAD

**Issue by carajillu** [molmod/psiflow#29]
README contains the following line:
`python -c 'import psiflow; psiflow.setup_slurm()`
but the module does not seem to have that function, however 
`psiflow.setup_slurm_config()`
exist and seems to do what the README file says, so I guess I'm just flagging a typo.

**Comment by svandenhaute** [comment]
Thanks for reporting this -- should be fixed now.

The SLURM quickstart is a new feature. We have tried to generalize the detection of the partitions and available hardware as much as possible across different clusters we have access to, but if the setup script somehow is not compatible with your HPC, please feel free to open a different issue.
