### ISSUE TITLE
quench() does not change the walkers' starting point

### ISSUE THREAD

**Issue by mbocus** [molmod/psiflow#41]
Hi!

When trying to run a basic umbrella sampling simulation with mace_mp0 the quench function does not seem to update the starting point of the walkers.
```
mace_mp0_small = MACEHamiltonian.mace_mp0(size="small")
mace_mp0_large = MACEHamiltonian.mace_mp0(size="large")

data_init = Dataset.load(Path.cwd() / 'train.xyz')

umbrella_centers = np.linspace(2.3, 4.4, 80)
for model_name, model in {"mace_mp0_small": mace_mp0_small, "mace_mp0_large": mace_mp0_large}.items():
    walkers = []
    savedir = path_output / model_name
    if not savedir.is_dir():
        savedir.mkdir()

    for center in umbrella_centers:
        bias = get_bias(kappa=3500.0, center=center)
        hamiltonian = model + bias
        walker = Walker(data_init[0], hamiltonian, temperature=623)
        walkers.append(walker)

    quench(walkers, data_init)
    outputs = sample(walkers, steps=100000, step=10)
    for i, output in enumerate(outputs):
        output.trajectory.save(savedir / 'U{}.xyz'.format(i))
```

Expected behavior: the walkers start from the most favorable structure. Observed behavior: all walkers start from data_init[0]

I'm using psiflow 4.0.0-rc1 - commit id "720fee3219260ff370e274ad579f103d2257871a" with the psiflow:v4.0.0-rc1_rocm5.6 container.

Thanks in advance for the help,
Massimo

**Comment by svandenhaute** [comment]
I don't immediately see anything wrong here. Can you try and evaluate the PLUMED bias right before creating a new walker? Get the index of the lowest value, and verify that the index changes with each iteration. 

You can use something like this in your for loop:
```py
energies = bias.compute(data_init, 'energy').result()
print(np.argmax(energies))
```

**Comment by svandenhaute** [comment]
Something to keep in mind of: the PLUMED Python driver *does not* deal well with comments an input file.

**Comment by svandenhaute** [comment]
Can you try and quench the walkers with `hamiltonian = bias` i.e. without MACE-MP0? Perhaps there is a structure in your dataset for which MACE-MP0 thinks it's ridiculously low-energy, and that would mess with the quenching.

**Comment by mbocus** [comment]
I did repeat the simulations with both `hamiltonian = bias` and `hamiltonian = model`; with the bias, the starting structure is always `data_init[0]`. With model, on the other hand, another structure is selected (which differs between the 'large' and 'small' model - presumably it is the one the model thinks is the lowest in energy). So it seems the issue is really related to having a plumed bias in the hamiltonian.

**Comment by svandenhaute** [comment]
OK, can you compute the bias energy in the for loop and print the minimum energy? On 25 Sep 2024, at 10:34, mbocus ***@***.***> wrote:﻿
I did repeat the simulations with both hamiltonian = bias and hamiltonian = model; with the bias, the starting structure is always data_init[0]. With model, on the other hand, another structure is selected (which differs between the 'large' and 'small' model - presumably it is the one the model thinks is the lowest in energy). So it seems the issue is really related to having a plumed bias in the hamiltonian.

**Comment by mbocus** [comment]
Alright, so there seems to be something strange going on with the energies. Occasionally (I cannot pinpoint any pattern) the first value of the energy array is NaN. If I try to print the energies at a specific position - which should correspond to the same structure evaluate with an umbrella whose center is gradually shifted - I do not get a smooth parabola as I should but somehow 2 parabolas (see picture). The points that are shifted are different all times. 

In the figure the bias energy is plotted for the 80 umbrella centers referred to a single structure in data_init. The blue line is for the second structure while the orange line for the third structure.
![image](https://github.com/user-attachments/assets/4748bdf1-ec4c-4652-b91f-405d616b7fa6)

**Comment by mbocus** [comment]
Ok so there is something ever weirder: when I make a dataset with a single structure (the first one in the original data_init) and I run the simple evaluation:

```
PLUMED_INPUT = """
UNITS LENGTH=A ENERGY=kj/mol TIME=fs

WHOLEMOLECULES ENTITY0=53,64,88,106,110,113-121,109,111,112

C1: COORDINATION GROUPA=53,64,88,106 GROUPB=110 R_0=2.0
C4: COORDINATION GROUPA=113-121 GROUPB=109,111,112 R_0=1.4
C5: COORDINATION GROUPA=113-121 GROUPB=53,64,88,106 R_0=1.4

CV: MATHEVAL ARG=C1,C4,C5 FUNC=(2/sqrt(5))*x+sin(acos(2/sqrt(5)))*(y-z) PERIODIC=NO
"""

def get_bias(kappa: float, center: float):
    plumed_input = PLUMED_INPUT
    plumed_input += '\n'
    plumed_input += 'RESTRAINT ARG=CV KAPPA={} AT={}\n'.format(kappa, center)
    return PlumedHamiltonian(plumed_input)


def main(path_output):
    data = Dataset.load(Path.cwd() / 'data.xyz')

    umbrella_centers = np.linspace(2.3, 4.4, 80)
    for i, center in enumerate(umbrella_centers):
        bias = get_bias(kappa=3500.0, center=center)
        energies = bias.compute(data, 'energy').result()
        print(energies)

if __name__=='__main__':
    path_output = Path.cwd() / 'trajectories'
    with psiflow.load():
        main(path_output)
```

I do get random NaNs in the output. What is even weirder is that if I run the script a second time the NaNs are no longer in the same position and the smaller values are not exactly the same (see attached outputs).

[out_run1.txt](https://github.com/user-attachments/files/17134200/out_run1.txt)
[out_run2.txt](https://github.com/user-attachments/files/17134201/out_run2.txt)

**Comment by svandenhaute** [comment]
My god, what a bug -- thanks for reporting this.

For some reason, PLUMED wants the positions array to be copied explicitly *only sometimes*. Adding a copy statement to this line fixed it:

https://github.com/molmod/psiflow/blob/e863bb6da536ddeebb1e6167b127ead14323a762/psiflow/functions.py#L134

Reinstall psiflow from the main branch -- it should solve the issue.

**Comment by mbocus** [comment]
Great, thanks for catching the bug! Now the bias evaluation on a single structure appears to work as intended. However, when I go back to the original umbrella sampling script, the main job keeps submitting short ModelEvaluation jobs and there is no sign of sampling. It looks like the script is somehow stuck at `quench()`. Any idea why that would happen?
My input scripts as well as the parsl.log are in attachment, there is no additional output produced.
[parsl.log](https://github.com/user-attachments/files/17174480/parsl.log)
[lumi.txt](https://github.com/user-attachments/files/17174483/lumi.txt)
[run.txt](https://github.com/user-attachments/files/17174484/run.txt)

**Comment by svandenhaute** [comment]
It looks like your LUMI config still loads `rocm/5.6`, which has been removed in the recent update -- you should now use `rocm/6.0.3`

**Comment by mbocus** [comment]
Apparently the problem was due to an unrelated issue (rocm version did not matter at the end), which is now also solved. 
I have been able to test the new main and everything works as expected, the walkers start from the right structure and the bias evaluation is correct. 

Thanks a lot for fixing the issue and the swift support!
