### ISSUE TITLE
Connection refused for ModelEvaluation jobs on LUMI

### ISSUE THREAD

**Issue by mbocus** [molmod/psiflow#42]
When running a simple psiflow-driven simulation using the mace_mp0 model on LUMI, the ModelEvaluation jobs produce an unexpected connection error when they start to run. This seems to be partially correlated with a recent cluster update, although I was able to have some jobs running regularly up until last week. Various combinations of modules/containers all produce the same error. No error is produced by the main process or is printed out by parsl.
The error file produced by the submission script of the ModelEvaluation job can be found in the attachment. 

Thanks in advance for the help,
Massimo
[parsl.ModelEvaluation.block-23.1727822876.8456078.txt](https://github.com/user-attachments/files/17221426/parsl.ModelEvaluation.block-23.1727822876.8456078.txt)

**Comment by mbocus** [comment]
This issue kind of fixed itself, simulations are now running normally.

**Comment by picnudde** [comment]
It appears I am observing the same issue now again, but during CP2K evaluations on the standard partition of LUMI. I also get the Connection Refused error message.

**Comment by picnudde** [comment]
The psiflow_internal folder and input configs are in the attached zip file. (I deleted the context_dir folder because the file was too big to upload otherwise)
[Psiflow.zip](https://github.com/user-attachments/files/17332128/Psiflow.zip)

**Comment by svandenhaute** [comment]
It appears that I accidentally hardcoded a completely wrong address in WQ execs. It should be fixed in commit e79ae8e -- can you reinstall from the latest main and verify that everything again works as expected?

**Comment by picnudde** [comment]
Great, everything runs as expected now. Thanks a lot!

**Comment by svandenhaute** [comment]
Great to hear -- one less heisenbug :)
