### ISSUE TITLE
TypeCheckError on simple dataset evaluation

### ISSUE THREAD

**Issue by mbocus** [molmod/psiflow#49]
Hello, 

I was performing a very simple dataset evaluation with CP2K on an unlabeled dataset. The CP2K jobs are submitted but a TypeCheckError immediately pops up in the parsl.log. This is the code I'm using:

```
def main():
    with open('cp2k.inp') as f:
        cp2k_input = f.read()
        cp2k = CP2K(cp2k_input)

    fn_dataset = Path.cwd() / 'initial_dataset_eval.xyz'
    if fn_dataset.exists():
        initial_dataset_eval = Dataset.load(fn_dataset)
    else:
        initial_dataset = Dataset.load(Path.cwd() / 'initial_dataset.xyz')
        initial_dataset_eval = initial_dataset.evaluate(cp2k)
        initial_dataset_eval.save(fn_dataset)
```

The parsl.log in DEBUG mode is attached. No new dataset is saved once the CP2K jobs are finished and the main process dies. Any clue where the error might originate from? 

Thanks!
Massimo
[parsl.log](https://github.com/user-attachments/files/17843785/parsl.log)

**Comment by svandenhaute** [comment]
Hmm weird, that type of execution is covered in one of the tests in `tests/test_reference.py` so I'm surprised about a `TypeCheckError`. Did the CP2K evaluations complete successfully based on what you see in the task logs?

**Comment by mbocus** [comment]
All CP2K evaluations completed successfully, aside from that TypeCheckError and the fact that no output is saved I cannot see anything wrong in the execution.

**Comment by svandenhaute** [comment]
Just noticed that one of the tests in `tests/test_reference.py` did not pass though I assumed it did. Can you retry from 0f6ab9c ?

**Comment by mbocus** [comment]
Yes, that seems to indeed have fixed the issue. Many thanks for the help!
