### ISSUE TITLE
PRINT_LEVEL LOW or SILENT in CP2K input file

### ISSUE THREAD

**Issue by ArnoutMaet** [molmod/psiflow#50]
Hello,

The CP2K output parser searches for atomic coordinates and returns a `NullState` if it does not find any. However, no atomic coordinates are included in the CP2K output file if `PRINT_LEVEL` (default = `MEDIUM`) is set explicitly set to `LOW` or `SILENT` in the input file. 
Is it possible to implement a check which sets `PRINT_LEVEL` to `MEDIUM` if it detects a `LOW` or `SILENT` setting?

Thanks in advance.
Arnout

**Comment by svandenhaute** [comment]
Good find -- should be fixed with 6f5149a
