### ISSUE TITLE
add_atomic_energies does not seem to work

### ISSUE THREAD

**Issue by mbocus** [molmod/psiflow#51]
Hello!

I am initializing a MACE model with psiflow using the latest version. I am using the simple set of commands:

```
model = MACE(
    r_max=6.5,
    max_L=2,
    num_channels=16,
    energy_weight=200,
    batch_size=16,
    lr=0.005,
    num_radial_basis=10,
    patience=10,
)

model.add_atomic_energy('H', 1.0) #cp2k.compute_atomic_energy('H', box_size=6))
model.add_atomic_energy('O', 8.0) #cp2k.compute_atomic_energy('O', box_size=6))
model.add_atomic_energy('Al', 13.0) #cp2k.compute_atomic_energy('Al', box_size=6))
model.add_atomic_energy('Si', 14.0) #cp2k.compute_atomic_energy('Si', box_size=6))

train, valid = data.split(0.9, shuffle=True)
model.initialize(train)
model.train(train, valid)
```

Either using cp2k.compute_atomic_energy or explicitly setting a number results in the following line in the model initialization output: 

```
2024-11-25 13:05:38.446 INFO: Atomic Energies not in training file, using command line argument E0s
2024-11-25 13:05:38.446 INFO: Computing average Atomic Energies using least squares regression
```

For the rest, the training seems to start normally after the initialization (but without the correct atomic energies). The parsl.log does not show explicit errors.

**Comment by svandenhaute** [comment]
Psiflow's atomic energies are entirely separate from MACE, so it is entirely the intention to get MACE to perform an additional estimate of the average per-atom *formation* energy and use that as offset in addition to the offset applied by psiflow using the `atomic_energies` dict in the `MACE` model instance.

**Comment by mbocus** [comment]
Very clear, thank you very much for the detailed explanation!
